services:
  endstone:
    container_name: endstone-qqsync
    image: ghcr.io/yuexps/endstone-qqsync-plugin:latest
    init: true
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
    volumes:
      - ./logs:/app/logs:rw
      - ./lagrange:/app/lagrange:rw
      - ./bedrock_server:/app/endstone/bedrock_server:rw
    environment:
      - TZ=Asia/Shanghai
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
